# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #

# Auto-generated by //oss/mojo-gpu-puzzles/solutions:generate_test_args_bzl
# Run `./bazelw run //oss/mojo-gpu-puzzles/solutions:update_test_args` to regenerate.

"""Maps Mojo solution files to the command-line flags they accept.

Files absent from this mapping run as a single test with no arguments.
Files present in this mapping get one test target per flag.
"""

TEST_ARGS = {
    "p13/p13.mojo": ["--block-boundary", "--simple"],
    "p14/p14.mojo": ["--simple"],
    "p16/p16.mojo": ["--idiomatic-tiled", "--naive", "--single-block", "--tiled"],
    "p22/p22.py": ["--backward", "--fused", "--unfused"],
    "p23/p23.mojo": ["--benchmark", "--elementwise", "--manual-vectorized", "--tiled", "--vectorized"],
    "p24/p24.mojo": ["--benchmark", "--functional", "--kernel", "--traditional"],
    "p25/p25.mojo": ["--average", "--broadcast-basic", "--broadcast-conditional", "--broadcast-shuffle-coordination", "--neighbor"],
    "p26/p26.mojo": ["--conditional-max", "--pair-swap", "--parallel-max", "--partition", "--prefix-sum"],
    "p27/p27.mojo": ["--block-sum-dot-product", "--histogram", "--normalize", "--traditional-dot-product"],
    "p29/p29.mojo": ["--double-buffer", "--multi-stage"],
    "p34/p34.mojo": ["--advanced", "--coordination", "--reduction"],
    "p35/p35.mojo": ["--aligned", "--benchmark", "--scalar", "--unaligned"],
}
